# fly.toml file generated for metrics-be on 2023-01-16T15:20:02+07:00

app = "metrics-be"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  [build.args]
    NODE_VERSION = "14"
    PHP_VERSION = "8.1"

[env]
  APP_ENV = "production"
  APP_URL = "https://metrics-be.fly.dev"
  FE_URL= "https://metrics-fe.fly.dev"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  APP_NAME="Metrics"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  DB_CONNECTION="pgsql"
  DB_HOST="metrics-db.internal"
  DB_PORT="5432"
  DB_DATABASE="metrics_be"
  DB_USERNAME="postgres"
  DB_PASSWORD="TMDoUEfIk7m7wKf"
  MAIL_MAILER="smtp"
  MAIL_HOST="smtp.gmail.com"
  MAIL_PORT="587"
  MAIL_USERNAME="metricsfarcap@gmail.com"
  MAIL_PASSWORD="bzlkamddlrvychst"
  MAIL_ENCRYPTION="tls"
  MAIL_FROM_ADDRESS="metricsfarcap@gmail.com"
  MAIL_FROM_NAME="Metrics"


[deploy]
  release_command = "php /var/www/html/artisan storage:link"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
