# fly.toml file generated for metrics-api on 2023-02-21T13:04:00+07:00

app = "metrics-api"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  [build.args]
    NODE_VERSION = "14"
    PHP_VERSION = "8.1"

[env]
  APP_ENV = "production"
  APP_NAME = "Metrics"
  APP_URL = "https://metrics-api.fly.dev"
  COUNTRY_ID = "102"
  DB_CONNECTION = "pgsql"
  DB_DATABASE = "metrics_be"
  DB_HOST = "metrics-db.internal"
  DB_PASSWORD = "TMDoUEfIk7m7wKf"
  DB_PORT = "5432"
  DB_USERNAME = "postgres"
  FE_URL = "https://metrics-fe.fly.dev"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  MAIL_ENCRYPTION = "tls"
  MAIL_FROM_ADDRESS = "metricsfarcap@gmail.com"
  MAIL_FROM_NAME = "Metrics"
  MAIL_HOST = "smtp.gmail.com"
  MAIL_MAILER = "smtp"
  MAIL_PASSWORD = "bzlkamddlrvychst"
  MAIL_PORT = "587"
  MAIL_USERNAME = "metricsfarcap@gmail.com"
  QUEUE_CONNECTION = "database"

[experimental]
  auto_rollback = true

[processes]
  app = ""
  cron = "cron -f"
  worker = "php /var/www/html/artisan queue:work"

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
